# https://taskfile.dev

################################################################################################
#
# DISCLAIMER:
#
# This tool is strictly for improving the developer experience and should not be used in our
# CI/CD pipelines! DO NOT use tasks to implement continous integration since we already have
# Skaffold for that purpose. Using Skaffold for CI/CD ensures that we have a consistent and
# reliable way to build, test, and deploy our applications.
# 
# This tool is only to augment local development using Skaffold and troubleshooting convenience.
#
################################################################################################

version: '3'

includes:
  example:
    taskfile: .task/example/Taskfile.yml
    aliases: [ex]
  colima:
    taskfile:  .task/colima/Taskfile.yml
    aliases: [cl]
  docker:
    taskfile: .task/docker/Taskfile.yml
    aliases: [dk]
  kubectl:
    taskfile: .task/kubectl/Taskfile.yml
    aliases: [kc]
  terraform:
    taskfile: .task/terraform/Taskfile.yml
    aliases: [tf]
  skaffold:
    taskfile: .task/skaffold/Taskfile.yml
    aliases: [sk]
  git: .task/git/Taskfile.yml
  gcp: .task/gcp/Taskfile.yml
  mosh: .task/mosh/Taskfile.yml
  debug: .task/debug/Taskfile.yml
#   docker: ./docker # docker image run [gcloud, skaffold, terraform, go, python, nodejs, etc.]
#   env: ./env

silent: true
# output: prefixed
# set: [pipefail]
# shopt: [globstar]

vars:
  TODAY: '{{ now | date "2006-01-02T15:04:05-07:00" }}'
  black: \033[:0;30m
  red: \033[:0;31m
  green: \033[:0;32m
  orange: \033[:0;33m
  blue: \033[:0;34m
  purple: \033[:0;35m
  cyan: \033[:0;36m
  light_gray: \033[:0;37m
  dark_gray: \033[:1;30m
  light_red: \033[:1;31m
  light_green: \033[:1;32m
  yellow: \033[:1;33m
  light_blue: \033[:1;34m
  light_purple: \033[:1;35m
  light_cyan: \033[:1;36m
  white: \033[:1;37m
  nocolor: \u001b[0m
  reversed: \u001b[7m

env:
  ENV: dev

dotenv: ['.env', '.env_{{.ENV}}', '{{.HOME}}/.env', '{{.HOME}}/.env_{{.ENV}}']

tasks:

  default:
    desc: List all tasks
    prefix: ⚙️ 
    cmds:
      - task {{default "--list" .CLI_ARGS}}

  # default-selective:
  #   desc: List selective tasks
  #   prefix: ⚙️ 
  #   cmds:
  #     - [ -n "$({{.CLI_ARGS}})" ] && task -l | grep {{.CLI_ARGS}}


  open:
    desc: Open main taskfile
    prefix: ⚙️
    cmds:
      - open {{.HOME}}/Taskfile.yml
    silent: true
